// Data is generally from Wikipedia.
export const languagesToCountries = {
  German: ["de", "at", "ch", "li"],
  Ukrainian: ["ua"],
  Welsh: ["gb"],
  // This is arbitrarily all the countries Wikipedia lists as having more than
  // 33.3% French proficiency.
  French: [
    "fr",
    "be",
    "ch",
    "mc",
    "mu",
    "ga",
    "cg",
    "tn",
    "sc",
    "cd",
    "dj",
    "tg",
    "cm",
    "km",
    "ci",
    "ma",
    "bj",
    "ca",
  ],
  Afrikaans: ["za", "na"],
  Finnish: ["fi"],
  Japanese: ["jp"],
  Polish: ["pl"],
  "Mandarin Chinese": ["cn"],
  Catalan: ["es", "ad"],
  Faroese: ["fo"],
  Arabic: [
    "dz",
    "bh",
    "km",
    "dj",
    "eg",
    "iq",
    "jo",
    "kw",
    "lb",
    "ly",
    "mr",
    "ma",
    "om",
    "ps",
    "qa",
    "sa",
    "so",
    "sd",
    "sy",
    "tn",
    "ae",
    "ye",
  ],
  Romanian: ["ro", "md"],
  Spanish: [
    "es",
    "gq",
    "ar",
    "bo",
    "cl",
    "co",
    "cr",
    "cu",
    "do",
    "ec",
    "sv",
    "gt",
    "hn",
    "mx",
    "ni",
    "pa",
    "py",
    "pe",
    "uy",
    "ve",
  ],
  Croatian: ["hr"],
  Russian: ["ru"],
  Cantonese: ["cn"],
  Hawaiian: ["us"],
  "Haitian Creole": ["ht"],
  "Old English": ["gb"],
  English: [
    "gb",
    "us",
    "ca",
    "au",
    "ie",
    "nz",
    "bs",
    "bb",
    "in",
    "bz",
    "bw",
    "fj",
    "gm",
    "gh",
    "gd",
    "gy",
    "jm",
    "ke",
    "lr",
    "mw",
    "fm",
    "ng",
    "pg",
    "ph",
    "kn",
    "vc",
    "sl",
    "sg",
    "sb",
    "za",
    "ss",
    "sd",
    "tt",
    "ug",
    "vu",
    "zm",
    "zw",
  ],
  Norwegian: ["no"],
  Serbian: ["rs"],
  Basque: ["es", "fr"],
  Zulu: ["za", "ls"],
  Hebrew: ["il"],
  Hindi: ["in"],
  Greek: ["gr"],
  Maltese: ["mt"],
  Korean: ["kp", "kr"],
  Swedish: ["se"],
  Czech: ["cz"],
  Turkish: ["tr", "cy"],
  Persian: ["ir"],
  Bengali: ["bd", "in"],
  Hungarian: ["hu"],
  Teochew: ["cn"],
  Amharic: ["et"],
  Kikongo: ["cd", "cg"],
  Bulgarian: ["bg"],
  Ainu: ["jp"],
  Cherokee: ["us"],
  Thai: ["th"],
  Irish: ["ie", "gb"],
  Urdu: ["pk", "in"],
  Quechua: ["ar", "bo", "cl", "co", "ec", "pe"],
  Tagalog: ["tl"],
  Guarani: ["py"],
  Italian: ["it", "sm", "va", "ch"],
  Xhosa: ["za", "ls"],
  Macedonian: ["mk"],
  Tajik: ["tj"],
  Kannada: ["in"],
  Indonesian: ["id"],
  Aromanian: ["gr", "al", "mk", "bg", "ro", "rs"],
  "Scottish Gaelic": ["gb"],
  Maori: ["nz"],
  Latin: ["va"],
  Danish: ["dk"],
  Georgian: ["ge"],
  Tamil: ["in", "lk", "my"],
  Swahili: ["tz", "ke"],
  Betawi: ["id"],
  Latvian: ["lv"],
  "Central Atlas Tamazight": ["ma"],
  Javanese: ["id"],
  Malay: ["my"],
  Jeju: ["kr"],
  "Antarctic English": ["aq"],
  Vietnamese: ["vn"],
  Slovene: ["si"],
  Lao: ["la"],
  Venetian: ["it"],
  Plautdietsch: ["de"],
  Azerbaijani: ["az"],
  Baoule: ["ci"],
  Fijian: ["fj"],
  Portuguese: ["pt", "br", "ao", "cv", "tl", "gq", "gw", "mo", "mz", "st"],
  Estonian: ["ee"],
  Oroqen: ["ru", "cn"],
  Chechen: ["ru"],
  Armenian: ["am"],
  Uzbek: ["uz"],
  Kikuyu: ["ke"],
  Inuktitut: ["ca"],
  "Tok Pisin": ["pg"],
  Ga: ["gh"],
  "Basque-Icelandic Pidgin": ["is"],
  Chamicuro: ["pe"],
  Assamese: ["in"],
  Filipino: ["ph"],
  Yoruba: ["bj", "ng", "tg"],
};
