<script>
</script>

<main class="container">
	<h1>Phonology</h1>

	<h2>Syllables</h2>
	<p>Allowed syllable structures are CV, CVC, VC, and V (only as a starting syllable)</p>
	<p>CV, VC turns into CVVC as a diphthong</p>

	<h2>Vowels</h2>
	<table>
		<thead>
			<tr>
				<th>Front</th>
				<th>Central</th>
				<th>Back</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>i</td>
				<td>ə</td>
				<td>u</td>
			</tr>
			<tr>
				<td>e</td>
				<td></td>
				<td>o</td>
			</tr>
			<tr>
				<td>a</td>
				<td></td>
				<td></td>
			</tr>
		</tbody>
	</table>

	<h2>Consonants</h2>
	<table>
		<thead>
			<tr>
				<th></th>
				<th>Bilabial</th>
				<th>Alveolar</th>
				<th>Post-Alveolar</th>
				<th>Palatal</th>
				<th>Velar</th>
				<th>Uvular</th>
				<th>Glottal</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><b>Nasal</b></td>
				<td>m</td>
				<td>n</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><b>Unvoiced plosive</b></td>
				<td>p</td>
				<td>t</td>
				<td></td>
				<td></td>
				<td>k</td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><b>Voiced plosive</b></td>
				<td>b</td>
				<td>d</td>
				<td></td>
				<td></td>
				<td>g</td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><b>Unvoiced affricate</b></td>
				<td></td>
				<td>t͡s</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><b>Voiced affricate</b></td>
				<td></td>
				<td></td>
				<td>dʒ</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><b>Unvoiced fricative</b></td>
				<td>f</td>
				<td></td>
				<td>ʃ</td>
				<td>ç</td>
				<td>x</td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><b>Voiced fricative</b></td>
				<td>v</td>
				<td></td>
				<td>ʒ</td>
				<td></td>
				<td>ɣ</td>
				<td>ʁ</td>
				<td></td>
			</tr>
			<tr>
				<td><b>Approximant</b></td>
				<td>w</td>
				<td>l</td>
				<td></td>
				<td>j</td>
				<td>(w)</td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><b>Trill</b></td>
				<td></td>
				<td>r</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
		</tbody>
	</table>
</main>